<?php


// Translation of file /vendor/diversen/simple-php-classes/src/imap.php

$_COS_LANG_MODULE['No title'] = 'No title';

// Translation of file /vendor/diversen/simple-php-classes/src/moduleloader.php

$_COS_LANG_MODULE['filter_'] = 'filter_';

// Translation of file /vendor/diversen/simple-php-classes/src/user/defaultProfile.php

$_COS_LANG_MODULE['(Admin) Edit profile'] = '(Admin) Edit profile';
$_COS_LANG_MODULE['Logout'] = 'Logout';

// Translation of file /vendor/diversen/simple-php-classes/src/html/helpers.php

$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['View'] = 'View';
$_COS_LANG_MODULE['Submit'] = 'Submit';

// Translation of file /vendor/diversen/simple-php-classes/src/upload/blob.php

$_COS_LANG_MODULE['File does not exists'] = 'File does not exists';
$_COS_LANG_MODULE['File is to large.'] = 'File is to large.';
$_COS_LANG_MODULE['Max size is '] = 'Max size is ';
$_COS_LANG_MODULE['This Content type is not allowed'] = 'This Content type is not allowed';

// Translation of file /vendor/diversen/simple-php-classes/src/user.php

$_COS_LANG_MODULE['You can not access this page, because your account has been locked!'] = 'You can not access this page, because your account has been locked!';

// Translation of file /vendor/diversen/simple-php-classes/src/pagination.php

$_COS_LANG_MODULE['Previous'] = 'Previous';
$_COS_LANG_MODULE['Next page'] = 'Next page';
$_COS_LANG_MODULE['Page'] = 'Page';

// Translation of file /vendor/diversen/simple-php-classes/src/upload.php

$_COS_LANG_MODULE['File exceeds php.ini settings'] = 'File exceeds php.ini settings';
$_COS_LANG_MODULE['File exceeds max size'] = 'File exceeds max size';
$_COS_LANG_MODULE['File was only partial uploaded'] = 'File was only partial uploaded';
$_COS_LANG_MODULE['No file was uploaded'] = 'No file was uploaded';
$_COS_LANG_MODULE['No temp dir exists'] = 'No temp dir exists';
$_COS_LANG_MODULE['Could not write to file system'] = 'Could not write to file system';
$_COS_LANG_MODULE['Unknow upload error'] = 'Unknow upload error';
$_COS_LANG_MODULE['File already exists'] = 'File already exists';
$_COS_LANG_MODULE['Could not move file.'] = 'Could not move file.';
$_COS_LANG_MODULE['Mime type is not allowed. '] = 'Mime type is not allowed. ';
$_COS_LANG_MODULE['These mime types are allowed '] = 'These mime types are allowed ';
$_COS_LANG_MODULE['File is to large'] = 'File is to large';

// Translation of file /vendor/diversen/simple-php-classes/src/imagescale.php

$_COS_LANG_MODULE['System could not load image driver'] = 'System could not load image driver';
$_COS_LANG_MODULE['System could not load image'] = 'System could not load image';
$_COS_LANG_MODULE['System could not resize image'] = 'System could not resize image';
$_COS_LANG_MODULE['System could not save image'] = 'System could not save image';

// Translation of file /vendor/diversen/simple-php-classes/src/html.php

$_COS_LANG_MODULE['File'] = 'File';
$_COS_LANG_MODULE['Max size'] = 'Max size';

// Translation of file /vendor/diversen/simple-php-classes/src/captcha.php

$_COS_LANG_MODULE['Enter number'] = 'Enter number';
$_COS_LANG_MODULE['CAPTCHA image'] = 'CAPTCHA image';
