<?php

// dummy file
lang::translate('filter_autolinkext_help');
lang::translate('filter_autolink_help');
lang::translate('filter_cosgeshi_help');
lang::translate('filter_cosmarkdown_help');
lang::translate('filter_cosmarkdownext_help');
lang::translate('filter_cosmedia_help');
lang::translate('filter_phphl_help');
lang::translate('filter_cosmarkdownNoFollow_help');
lang::translate('filter_stacklink_help');